# Generated by Django 4.2.17 on 2024-12-19 10:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_salesforceconnection_organization_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiusage',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apiusage',
            name='process_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apiusage',
            name='process_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apiusage',
            name='process_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apiusage',
            name='process_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='apiusage',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='salesforceconnection',
            name='org_type',
            field=models.CharField(choices=[('Production', 'Production'), ('Sandbox', 'Sandbox'), ('Developer', 'Developer'), ('ScratchOrg', 'ScratchOrg')], default='Production', max_length=10),
        ),
        migrations.CreateModel(
            name='ProcessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('api_usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_logs', to='users.apiusage')),
            ],
        ),
    ]
