# Generated by Django 4.2.17 on 2024-12-19 11:44

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentationsection',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
