# Generated by Django 4.2.17 on 2024-12-19 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0002_alter_documentationsection_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_codes', to='documentation.documentationsection')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example_text', models.TextField()),
                ('response_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='documentation.responsecode')),
            ],
        ),
    ]
