# Generated by Django 4.2.17 on 2024-12-16 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionoption',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
